### ISSUE TITLE
IE11: SCRIPT5009: 'Promise' is undefined

### ISSUE THREAD

**Issue by amygroshek** [Hyperobjekt/react-seda-search#4]
```
SCRIPT5009: 'Promise' is undefined
react-seda-search.min.js (24,61660)
```

<img width="617" alt="Screen Shot 2019-09-24 at 10 02 19 PM" src="https://user-images.githubusercontent.com/746182/65566041-51bb9300-df17-11e9-88b1-e97d90ce4dcb.png">

**Comment by amygroshek** [comment]
I'm now getting a similar error from another project file: 

```
SCRIPT5009: 'Promise' is undefined
react-seda-search.min.js (24,44903)
```

Refers to: 
<img width="606" alt="Screen Shot 2019-09-25 at 12 48 43 PM" src="https://user-images.githubusercontent.com/746182/65626261-d697c280-df92-11e9-94e8-ab5b043d426e.png">

**Comment by Lane** [comment]
hmm... there is no `utils.js` in this repo.  looks like this is from `react-seda-scatterplot`?  is that updated with the ie11 compatibility changes?

**Comment by amygroshek** [comment]
Yeah agreed, I see that there's no utils.js in the project... 

Here's the merge log. I'm working on branch `cross-browser-testing`, which also adds a babel step to the seda site script processing... 

```
commit 5758d1d41fbb6088cbddf2defa505d684f19fc55 (HEAD -> cross-browser-testing)
Merge: dee9abd 977f84e
Author: A Groshek <amy@amygroshek.com>
Date:   Wed Sep 25 12:37:23 2019 -0500

    Merge branch 'master' into cross-browser-testing

commit 977f84e871a01f76aa0a8c2242ba8a90ab67d917 (origin/master, master)
Merge: e7a1716 9fa1082
Author: Amy Groshek <amy@amygroshek.com>
Date:   Wed Sep 25 12:34:28 2019 -0500

    Merge pull request #33 from Hyperobjekt/fix/search-update

    update react-seda-search to ie11 compatible

commit 9fa10825c7b06bc3d5d140bdb0c0fb9684c101cc (origin/fix/search-update)
Author: Lane Olson <laneolson@gmail.com>
Date:   Wed Sep 25 11:30:33 2019 -0600

    update react-seda-search to ie11 compatible

**Comment by amygroshek** [comment]
Also, to answer your question, I did drop in a fresh build of the scatterplot. The error documented in #15 there is resolved, but it looks like seda-scatterplot isn't getting instantiated properly: 

<img width="777" alt="Screen Shot 2019-09-25 at 1 05 35 PM" src="https://user-images.githubusercontent.com/746182/65627550-37c09580-df95-11e9-929f-deba8c9e691d.png">

**Comment by amygroshek** [comment]
Tested again in master (this would have your work on babel for this component but not my changes to the container site scrips or scatterplot) the same error shows there (albeit with a lot of others): 

```
SCRIPT5009: 'Promise' is undefined
react-seda-search.min.js (24,44903)
```

<img width="722" alt="Screen Shot 2019-09-25 at 1 19 42 PM" src="https://user-images.githubusercontent.com/746182/65628509-2e382d00-df97-11e9-9fd8-fd01d84b02f3.png">

**Comment by Lane** [comment]
ah, okay, one of the libs that search uses has promises exposed.  can you try adding this polyfill before the search script loads?

```
<script src='https://polyfill.io/v3/polyfill.min.js?features=es2015%2CArray.prototype.filter%2CArray.prototype.find%2CArray.prototype.forEach%2CArray.prototype.includes%2CArray.prototype.map%2CArray.prototype.reduce%2CDate.now%2CJSON%2CObject.assign%2CPromise%2CPromise.prototype.finally%2Cconsole.log'></script>
```

**Comment by amygroshek** [comment]
On it.

**Comment by amygroshek** [comment]
@Lane if you are good with just loading the polyfill for the article pages I'll close this.

**Comment by Lane** [comment]
sounds good, i have it in a PR i just opened in the `seda-site` repo.
